menu:
  Home: /
  Archives: /archives
  #About: /about
  #Tags: /tags
  # Categories: /categories



# Social links
social:
  GitHub:
    key: github
    link: https://github.com/Boseny
  微博:
    key: weibo
    link: https://weibo.com/boseny
  知乎:
    key: zhihu
    link: https://www.zhihu.com/people/boseny
  Lofter:
    key: lofter
    link: http://boseny.lofter.com/
  # 等等
# duoshuo comment 已废弃
duoshuo: false
duoshuo_name:

# disqus comment
disqus: false
disqus_shortname: boseny-blog

# livere comment
livere: false
livere_uid: MTAyMC8zMzYwMC8xMDE1NQ==

#Gitment (Recommended Use) see https://imsun.net/posts/gitment-introduction/
Gitment: false
Gitment_client_id: 899f2000858ee48b7247
Gitment_client_secret: 4e3716f7e6a6d6bfb11b4d8c836d10eab9245178
Gitment_Github_id: nksckx
repo: WebPageComment

# youyan comment
youyan: false
youyan_uid: 2156653
# google analytics
googleTrackId: 

# google AdSenseId
AdSenseId: 

# 百度统计
baidu_analytics: 

toc:
  enable: true

# anchorjs
anchorjs: true

# sidebar search
search: true
# sidebar categories
categories: true
# sidebar links
links: false


draw: true
draw_maxNum: 10
draw_iconText: ❤
draw_color: red
